<a href="https://colab.research.google.com/github/Jatin-Miglani/Learn-ML/blob/main/Research_ML_Day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#NUMPY and how to create array using Numpy.

Numpy is used for Arrays.
It is a Package or a library in Python to perform mathematica operations on array.

We can also work on Multidimensional Arrays(1d,2d,3d).

An array is a group of homogeneous data.

List v/s Array:-

In [ ]:
a1=[1,2,3,4,5]
a2=[10,11,12,13,14]
#data type is int for both lists. List can store elements with different data Types.
a3=a1+a2
print(a3)

[1, 2, 3, 4, 5, 10, 11, 12, 13, 14]


In [ ]:
#items will not add they will concatenate. In List mathematical Operation can't be performed directly.


In [ ]:
import numpy as np
#as np means that wherever we will use numpy we will write np

In [ ]:
a1=np.array([1,2,3,4,5])
a2=np.array([11,12,13,14,15])
#now a1 and a2 are arrays
type(a1)

numpy.ndarray

In [ ]:
a3=a1+a2
a3

array([12, 14, 16, 18, 20])

In [ ]:
#arrays store homogeneous data.
a1 = np.array([1,2,3,4,5,6,7,8,9,10])
#look at number of square brackets to know the dimension of array.
#so it is 1-d Array.
a2= np.array([[1,2,3,4,5,6,7,8,9,10]])
#it is 2-d array.
a3= np.array([[1,2,3,4,5,6,7,8,9,10],[1,2,3,4,5,6,7,8,9,10],[1,2,3,4,5,6,7,8,9,10]])
#it is a 2-d array.


In [ ]:
print(a1.ndim)
#to check the dimension of array

1


In [ ]:
print(a2.ndim," ",a3.ndim)

2   2


In [ ]:
#3-d array Color Image and 2-d array Black-white image this is used for images.

In [ ]:
#How to count the number of dimensions in an array.
a1+a2+a2

array([[ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30]])

In [ ]:
#it add the first elements of array accoring to 1-d


In [ ]:
print(len(a1))
print(len(a2))
print(len(a3))


10
1
3


In [ ]:
print(a1.shape)

(10,)


In [ ]:
print(a2.shape)
print(a3.shape)


(1, 10)
(3, 10)


In [ ]:
#a1 has 10 elements only
#a2 has 10 elements in 1 element
#a3 has 10 elements each in the 3 elements.

In [ ]:
print(a1.dtype)

int64


In [ ]:
#it gives the data type of array.

In [ ]:
print(a2.dtype)
print(a3.dtype)


int64
int64


In [ ]:
a2.shape[1]

10

In [ ]:
#hence you can find shape of elements in an array.

In [ ]:
#How to generate random array. To generate random data in Numpy.



In [ ]:
np.random.randint(100)   #it will give you a single random number from 0 to 99

19

In [ ]:
# Generate random number but number should be same in all the systems.
np.random.seed(100) # any value b/w 0 to 2**32-1
np.random.randint(100)

8

In [ ]:
#seed value make random data fixed.
# 8 is fixed at 100. It is fixed in memory.

In [ ]:
np.random.randint(100,1000) #100 to 999

892

In [ ]:
#for generating multiple numbers we will write.
np.random.randint(100,1000,10)

array([935, 971, 955, 179, 450, 966, 153, 678, 838, 626])

In [ ]:
#it generate 10 samples in an array.
#it give 1-d array.


In [ ]:
np.random.randint(100,1000,(5,5))

array([[902, 852, 380, 755, 328],
       [975, 416, 670, 607, 749],
       [193, 186, 486, 767, 976],
       [515, 997, 241, 857, 823],
       [712, 104, 703, 935, 235]])

In [ ]:
#hence we got a 2-d array

In [ ]:
#all these are int data type. What if we want float. We will write:-

In [ ]:
np.random.uniform(100,1000,(5,5))

array([[835.8844409 , 402.50075511, 257.86940837, 435.54884166,
        105.11965662],
       [327.1837181 , 816.09625763, 113.72947412, 638.95903924,
        643.42408514],
       [194.63291687, 443.74910045, 132.82845093, 901.3704071 ,
        982.82877131],
       [153.94778994, 901.49135026, 619.21134946, 768.23172019,
        667.16554283],
       [623.65797316, 118.39521882, 289.02391991, 590.21639036,
        792.203654  ]])

In [ ]:
#here i get big decimal values. What if we want upto 2 decimal places. We will write.

a=np.random.uniform(100,1000,(5,5))
np.round(a,2)

array([[325.63, 357.31, 867.16, 977.51, 896.37],
       [423.56, 638.97, 419.32, 406.17, 260.27],
       [313.92, 140.38, 554.89, 438.63, 633.52],
       [666.95, 228.34, 940.46, 951.74, 642.07],
       [448.99, 426.87, 283.91, 349.09, 321.88]])

In [ ]:
np.ceil(a)

array([[326., 358., 868., 978., 897.],
       [424., 639., 420., 407., 261.],
       [314., 141., 555., 439., 634.],
       [667., 229., 941., 952., 643.],
       [449., 427., 284., 350., 322.]])

In [ ]:
#in ceil the decimals will get removed.

In [ ]:
#MATHEMATICAL FUNCTIONS.

In [ ]:
#ARRAY SLICING
np.random.seed(1)
arr=np.random.randint(1,20,(8,6))
arr

array([[ 6, 12, 13,  9, 10, 12],
       [ 6, 16,  1, 17,  2, 13],
       [ 8, 14,  7, 19,  6, 19],
       [12, 11, 15, 19,  5, 10],
       [18,  1, 14, 10, 10,  8],
       [ 2,  1, 18,  9, 14, 16],
       [11,  9,  8,  4,  7, 18],
       [ 4,  5, 18, 12, 13, 17]])

In [ ]:
arr[:,:]     #the first colon represents the rows and the second colon represent columns

array([[ 6, 12, 13,  9, 10, 12],
       [ 6, 16,  1, 17,  2, 13],
       [ 8, 14,  7, 19,  6, 19],
       [12, 11, 15, 19,  5, 10],
       [18,  1, 14, 10, 10,  8],
       [ 2,  1, 18,  9, 14, 16],
       [11,  9,  8,  4,  7, 18],
       [ 4,  5, 18, 12, 13, 17]])

In [ ]:
#here we get the complete array.
#waht if i want 7,19,6   15,19,5    14,10,10   18,9,14
#index of 7,19,6 row is 2 and of 18,9,14 is 6 but we will write [2:6] to print rows and [2:5] to print columns.

In [ ]:
arr[2:6,2:5]

array([[ 7, 19,  6],
       [15, 19,  5],
       [14, 10, 10],
       [18,  9, 14]])

In [ ]:
# i want single 19
arr[3:4,3:4]

array([[19]])

In [ ]:
#best practice for single element is [3,3] only row and column
arr[3,3]

19

In [ ]:
# ARRAY FUNCTIONS.

In [ ]:
arr

array([[ 6, 12, 13,  9, 10, 12],
       [ 6, 16,  1, 17,  2, 13],
       [ 8, 14,  7, 19,  6, 19],
       [12, 11, 15, 19,  5, 10],
       [18,  1, 14, 10, 10,  8],
       [ 2,  1, 18,  9, 14, 16],
       [11,  9,  8,  4,  7, 18],
       [ 4,  5, 18, 12, 13, 17]])

In [ ]:
print(arr.sum())  # it will take sum of each item. Everything will be added.

509


In [ ]:
print(arr.sum(axis=0))  #we got sum of each column.

[ 67  69  94  99  67 113]


In [ ]:
print(arr.sum(axis=1))  #we got sum of each row.


[62 55 73 72 61 60 57 69]


In [ ]:
print(arr.mean())
print(arr.mean(axis=0)) #column wise mean.
print(arr.mean(axis=1))  #row wise mean.



10.604166666666666
[ 8.375  8.625 11.75  12.375  8.375 14.125]
[10.33333333  9.16666667 12.16666667 12.         10.16666667 10.
  9.5        11.5       ]


In [ ]:
print(arr.max())
print(arr.max(axis=0)) #column wise
print(arr.max(axis=1)) #row wise


19
[18 16 18 19 14 19]
[13 17 19 19 18 18 18 18]


In [ ]:
#hence similarly for arr.min() and all.

In [ ]:
print(arr.argmin())   #gives the position of minimum number
print(arr.argmin(axis=0)) # column wise
print(arr.argmin(axis=1)) #row wise


8
[5 4 1 6 1 4]
[0 2 4 4 1 1 3 0]


In [ ]:
print(arr.argmax())   #gives the position of maximum number
print(arr.argmax(axis=0)) # column wise
print(arr.argmax(axis=1)) #row wise


15
[4 1 5 2 5 2]
[2 3 3 3 0 2 5 2]


In [ ]:
## Change shape or dimension of the array.
arr.shape


(8, 6)

In [ ]:
arr.ndim

2

In [ ]:
arr_1=arr.reshape(48)
arr_1

array([ 6, 12, 13,  9, 10, 12,  6, 16,  1, 17,  2, 13,  8, 14,  7, 19,  6,
       19, 12, 11, 15, 19,  5, 10, 18,  1, 14, 10, 10,  8,  2,  1, 18,  9,
       14, 16, 11,  9,  8,  4,  7, 18,  4,  5, 18, 12, 13, 17])

In [ ]:
arr_2=arr.reshape(6,8)
arr_3=arr.reshape(2,24)
arr_2

array([[ 6, 12, 13,  9, 10, 12,  6, 16],
       [ 1, 17,  2, 13,  8, 14,  7, 19],
       [ 6, 19, 12, 11, 15, 19,  5, 10],
       [18,  1, 14, 10, 10,  8,  2,  1],
       [18,  9, 14, 16, 11,  9,  8,  4],
       [ 7, 18,  4,  5, 18, 12, 13, 17]])

In [ ]:
arr_3

array([[ 6, 12, 13,  9, 10, 12,  6, 16,  1, 17,  2, 13,  8, 14,  7, 19,
         6, 19, 12, 11, 15, 19,  5, 10],
       [18,  1, 14, 10, 10,  8,  2,  1, 18,  9, 14, 16, 11,  9,  8,  4,
         7, 18,  4,  5, 18, 12, 13, 17]])

In [ ]:
arr_4=arr.reshape(3,2,8)
arr_4

array([[[ 6, 12, 13,  9, 10, 12,  6, 16],
        [ 1, 17,  2, 13,  8, 14,  7, 19]],

       [[ 6, 19, 12, 11, 15, 19,  5, 10],
        [18,  1, 14, 10, 10,  8,  2,  1]],

       [[18,  9, 14, 16, 11,  9,  8,  4],
        [ 7, 18,  4,  5, 18, 12, 13, 17]]])

In [ ]:
#you just have to make the combination =48 then you can convert or reshape.

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
#To convert the data type you have to use:-

arr.astype('float32')

array([[ 6., 12., 13.,  9., 10., 12.],
       [ 6., 16.,  1., 17.,  2., 13.],
       [ 8., 14.,  7., 19.,  6., 19.],
       [12., 11., 15., 19.,  5., 10.],
       [18.,  1., 14., 10., 10.,  8.],
       [ 2.,  1., 18.,  9., 14., 16.],
       [11.,  9.,  8.,  4.,  7., 18.],
       [ 4.,  5., 18., 12., 13., 17.]], dtype=float32)

In [ ]:
arr.astype('int32')

array([[ 6, 12, 13,  9, 10, 12],
       [ 6, 16,  1, 17,  2, 13],
       [ 8, 14,  7, 19,  6, 19],
       [12, 11, 15, 19,  5, 10],
       [18,  1, 14, 10, 10,  8],
       [ 2,  1, 18,  9, 14, 16],
       [11,  9,  8,  4,  7, 18],
       [ 4,  5, 18, 12, 13, 17]], dtype=int32)

In [ ]:
arr.astype('str')

array([['6', '12', '13', '9', '10', '12'],
       ['6', '16', '1', '17', '2', '13'],
       ['8', '14', '7', '19', '6', '19'],
       ['12', '11', '15', '19', '5', '10'],
       ['18', '1', '14', '10', '10', '8'],
       ['2', '1', '18', '9', '14', '16'],
       ['11', '9', '8', '4', '7', '18'],
       ['4', '5', '18', '12', '13', '17']], dtype='<U21')

In [ ]:
arr.astype('int64')

array([[ 6, 12, 13,  9, 10, 12],
       [ 6, 16,  1, 17,  2, 13],
       [ 8, 14,  7, 19,  6, 19],
       [12, 11, 15, 19,  5, 10],
       [18,  1, 14, 10, 10,  8],
       [ 2,  1, 18,  9, 14, 16],
       [11,  9,  8,  4,  7, 18],
       [ 4,  5, 18, 12, 13, 17]])

In [ ]:
arr=arr.astype('int64')  #then only it will change datatype

In [ ]:
#How to create some standard matrices.

In [ ]:
#how to generate zero matrix.
np.zeros((5,5),np.uint)   #unit is unsigned integer

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=uint64)

In [ ]:
np.ones((5,5),np.uint)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=uint64)

In [ ]:
np.identity((5),np.uint)  #to generate Identity Matrix whose diagonal is 1.

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=uint64)

In [ ]:
#out of topic
import random
mystr ="12345abcde"
length=10
random_str = " jatin".join(random.sample(mystr, length))
random_str

'c jatin1 jatine jatin2 jatind jatina jatin5 jatin4 jatin3 jatinb'